-- =============================================================================
-- SPARK-PENS Database Schema
-- Sistem Peminjaman Ruangan (Room Booking System)
-- Politeknik Elektronika Negeri Surabaya (PENS)
-- =============================================================================
-- 
-- Generated from Entity Framework Core Migrations
-- Last Updated: 2026-02-17
-- =============================================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================================================
-- USERS TABLE
-- =============================================================================
CREATE TABLE "Users" (
    "Id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Email" VARCHAR(255) NOT NULL,
    "Name" VARCHAR(255) NOT NULL,
    "Role" VARCHAR(50) NOT NULL DEFAULT 'User',
    "GoogleId" VARCHAR(255) NULL,
    "PasswordHash" VARCHAR(255) NULL,
    "HasPassword" BOOLEAN NOT NULL DEFAULT FALSE,
    "ResetToken" VARCHAR(255) NULL,
    "ResetExpiry" TIMESTAMP WITH TIME ZONE NULL,
    "CreatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

-- Index for faster lookups
CREATE INDEX "IX_Users_Email" ON "Users" ("Email");
CREATE INDEX "IX_Users_GoogleId" ON "Users" ("GoogleId");
CREATE INDEX "IX_Users_Role" ON "Users" ("Role");

-- =============================================================================
-- ROOMS TABLE
-- =============================================================================
CREATE TABLE "Rooms" (
    "Id" UUID NOT NULL DEFAULT uuid_generate_v4(),
    "Name" VARCHAR(100) NOT NULL,
    "Building" VARCHAR(100) NOT NULL,
    "Floor" INTEGER NOT NULL,
    "Capacity" INTEGER NOT NULL,
    "Description" TEXT NOT NULL,
    "IsAvailable" BOOLEAN NOT NULL DEFAULT TRUE,
    "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE,
    "CreatedDate" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_Rooms" PRIMARY KEY ("Id")
);

-- Index for faster lookups
CREATE INDEX "IX_Rooms_Name" ON "Rooms" ("Name");
CREATE INDEX "IX_Rooms_Building" ON "Rooms" ("Building");
CREATE INDEX "IX_Rooms_Floor" ON "Rooms" ("Floor");
CREATE INDEX "IX_Rooms_IsAvailable" ON "Rooms" ("IsAvailable");

-- =============================================================================
-- BOOKINGS TABLE
-- =============================================================================
CREATE TABLE "Bookings" (
    "Id" UUID NOT NULL DEFAULT uuid_generate_v4(),
    "RoomId" UUID NOT NULL,
    "RequesterName" VARCHAR(100) NOT NULL,
    "RequesterEmail" VARCHAR(255) NOT NULL,
    "RequesterPhone" TEXT NULL,
    "BookingDate" TIMESTAMP WITH TIME ZONE NULL,
    "BookingStartDate" TIMESTAMP WITH TIME ZONE NOT NULL,
    "BookingEndDate" TIMESTAMP WITH TIME ZONE NOT NULL,
    "Purpose" TEXT NOT NULL,
    "Status" TEXT NOT NULL DEFAULT 'Pending',
    "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE,
    "CreatedDate" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_Bookings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Bookings_Rooms_RoomId" FOREIGN KEY ("RoomId") 
        REFERENCES "Rooms" ("Id") ON DELETE RESTRICT
);

-- Index for faster lookups
CREATE INDEX "IX_Bookings_RoomId" ON "Bookings" ("RoomId");
CREATE INDEX "IX_Bookings_RequesterEmail" ON "Bookings" ("RequesterEmail");
CREATE INDEX "IX_Bookings_Status" ON "Bookings" ("Status");
CREATE INDEX "IX_Bookings_BookingStartDate" ON "Bookings" ("BookingStartDate");
CREATE INDEX "IX_Bookings_BookingEndDate" ON "Bookings" ("BookingEndDate");
CREATE INDEX "IX_Bookings_CreatedDate" ON "Bookings" ("CreatedDate");

-- Composite index for overlap checking
CREATE INDEX "IX_Bookings_RoomId_Status_Dates" ON "Bookings" ("RoomId", "Status", "BookingStartDate", "BookingEndDate");

-- =============================================================================
-- INSERT SAMPLE DATA (Optional - for testing)
-- =============================================================================

-- Insert sample rooms (uncomment to use)
-- INSERT INTO "Rooms" ("Id", "Name", "Building", "Floor", "Capacity", "Description", "IsAvailable", "IsDeleted", "CreatedDate")
-- VALUES 
--     (uuid_generate_v4(), 'Ruang Meeting A', 'Gedung A', 1, 10, 'Ruang meeting dengan kapasitas 10 orang, dilengkapi AC dan proyektor', TRUE, FALSE, NOW()),
--     (uuid_generate_v4(), 'Ruang Meeting B', 'Gedung A', 1, 8, 'Ruang meeting kecil untuk 8 orang', TRUE, FALSE, NOW()),
--     (uuid_generate_v4(), 'Ruang Seminar', 'Gedung B', 2, 50, 'Aula seminar besar dengan kapasitas 50 orang, dilengkapi sound system', TRUE, FALSE, NOW()),
--     (uuid_generate_v4(), 'Ruang Training', 'Gedung C', 3, 20, 'Ruang training dengan kapasitas 20 orang dan whiteboard', TRUE, FALSE, NOW()),
--     (uuid_generate_v4(), 'Lab Komputer 1', 'Gedung D', 1, 30, 'Laboratorium komputer dengan 30 unit PC', TRUE, FALSE, NOW()),
--     (uuid_generate_v4(), 'Lab Komputer 2', 'Gedung D', 2, 25, 'Laboratorium komputer dengan 25 unit PC', TRUE, FALSE, NOW()),
--     (uuid_generate_v4(), 'Ruang Dosen', 'Gedung A', 4, 5, 'Ruang diskusi untuk dosen', TRUE, FALSE, NOW()),
--     (uuid_generate_v4(), 'Aula Utama', 'Gedung Utama', 1, 100, 'Aula terbesar dengan kapasitas 100 orang', TRUE, FALSE, NOW());

-- =============================================================================
-- FUNCTIONS (Helper for overlap checking)
-- =============================================================================

-- Function to check booking overlap
CREATE OR REPLACE FUNCTION check_booking_overlap(
    p_room_id UUID,
    p_start_date TIMESTAMP WITH TIME ZONE,
    p_end_date TIMESTAMP WITH TIME ZONE,
    p_exclude_booking_id UUID DEFAULT NULL
)
RETURNS BOOLEAN AS $$
DECLARE
    v_overlap_exists BOOLEAN;
BEGIN
    SELECT EXISTS (
        SELECT 1 
        FROM "Bookings" b
        WHERE b."RoomId" = p_room_id
          AND b."IsDeleted" = FALSE
          AND b."Status" IN ('Pending', 'Approved')
          AND b."Id" != COALESCE(p_exclude_booking_id, '00000000-0000-0000-0000-000000000000'::uuid)
          AND b."BookingStartDate" < p_end_date
          AND b."BookingEndDate" > p_start_date
    ) INTO v_overlap_exists;
    
    RETURN v_overlap_exists;
END;
$$ LANGUAGE plpgsql;

-- Function to get available time slots for a room on a specific date
CREATE OR REPLACE FUNCTION get_available_slots(
    p_room_id UUID,
    p_date DATE,
    p_slot_duration INTERVAL DEFAULT '1 hour'::interval
)
RETURNS TABLE(slot_start TIME, slot_end TIME) AS $$
DECLARE
    v_day_start TIMESTAMP WITH TIME ZONE;
    v_day_end TIMESTAMP WITH TIME ZONE;
    v_current_time TIMESTAMP WITH TIME ZONE;
BEGIN
    -- Set working hours (8:00 AM - 6:00 PM)
    v_day_start := p_date AT TIME ZONE 'UTC';
    v_day_end := (p_date + INTERVAL '1 day') AT TIME ZONE 'UTC';
    
    -- Working hours: 08:00 - 18:00
    v_day_start := v_day_start + INTERVAL '8 hours';
    v_day_end := v_day_end + INTERVAL '18 hours';
    
    -- Generate time slots
    v_current_time := v_day_start;
    
    WHILE v_current_time < v_day_end LOOP
        -- Check if this slot overlaps with any booking
        IF NOT check_booking_overlap(p_room_id, v_current_time, v_current_time + p_slot_duration) THEN
            RETURN QUERY SELECT 
                CAST(v_current_time AS TIME),
                CAST(v_current_time + p_slot_duration AS TIME);
        END IF;
        
        v_current_time := v_current_time + p_slot_duration;
    END LOOP;
END;
$$ LANGUAGE plpgsql;

-- =============================================================================
-- VIEWS (For reporting)
-- =============================================================================

-- View for active bookings with room details
CREATE OR REPLACE VIEW v_active_bookings AS
SELECT 
    b."Id" AS booking_id,
    b."RequesterName",
    b."RequesterEmail",
    b."RequesterPhone",
    b."BookingStartDate",
    b."BookingEndDate",
    b."Purpose",
    b."Status",
    b."CreatedDate",
    r."Name" AS room_name,
    r."Building",
    r."Floor"
FROM "Bookings" b
INNER JOIN "Rooms" r ON b."RoomId" = r."Id"
WHERE b."IsDeleted" = FALSE
ORDER BY b."CreatedDate" DESC;

-- View for room availability summary
CREATE OR REPLACE VIEW v_room_availability AS
SELECT 
    r."Id" AS room_id,
    r."Name" AS room_name,
    r."Building",
    r."Floor",
    r."Capacity",
    r."IsAvailable",
    COUNT(b."Id") FILTER (WHERE b."Status" = 'Pending') AS pending_bookings,
    COUNT(b."Id") FILTER (WHERE b."Status" = 'Approved') AS approved_bookings,
    COUNT(b."Id") FILTER (WHERE b."Status" = 'Rejected') AS rejected_bookings
FROM "Rooms" r
LEFT JOIN "Bookings" b ON r."Id" = b."RoomId" AND b."IsDeleted" = FALSE
WHERE r."IsDeleted" = FALSE
GROUP BY r."Id", r."Name", r."Building", r."Floor", r."Capacity", r."IsAvailable";

-- =============================================================================
-- COMMENTS (Documentation)
-- =============================================================================

COMMENT ON TABLE "Users" IS 'User accounts for authentication. Roles: Admin, User';
COMMENT ON TABLE "Rooms" IS 'Available rooms for booking';
COMMENT ON TABLE "Bookings" IS 'Room booking requests';

COMMENT ON COLUMN "Users"."Role" IS 'User role: Admin (full access) or User (limited access)';
COMMENT ON COLUMN "Users"."GoogleId" IS 'Google OAuth ID for Google login users';
COMMENT ON COLUMN "Users"."HasPassword" IS 'Whether user has set a password (for Google users)';
COMMENT ON COLUMN "Users"."ResetToken" IS 'Token for password reset (valid for 30 minutes)';

COMMENT ON COLUMN "Rooms"."Building" IS 'Building name (e.g., Gedung A, Gedung B)';
COMMENT ON COLUMN "Rooms"."Floor" IS 'Floor number';
COMMENT ON COLUMN "Rooms"."Capacity" IS 'Maximum number of people';
COMMENT ON COLUMN "Rooms"."IsAvailable" IS 'Whether room is available for booking';

COMMENT ON COLUMN "Bookings"."RoomId" IS 'Foreign key to Rooms table';
COMMENT ON COLUMN "Bookings"."BookingStartDate" IS 'Booking start time (UTC)';
COMMENT ON COLUMN "Bookings"."BookingEndDate" IS 'Booking end time (UTC)';
COMMENT ON COLUMN "Bookings"."Status" IS 'Booking status: Pending, Approved, Rejected';

-- =============================================================================
-- END OF SCHEMA
-- =============================================================================

